-- AlterTable
ALTER TABLE "Tape" ALTER COLUMN "audioType" SET NOT NULL,
ALTER COLUMN "catalogNumber" SET NOT NULL,
ALTER COLUMN "distributor" SET NOT NULL,
ALTER COLUMN "packagingType" SET NOT NULL,
ALTER COLUMN "productionCompany" SET NOT NULL,
ALTER COLUMN "rating" SET NOT NULL,
ALTER COLUMN "releaseYear" SET NOT NULL,
ALTER COLUMN "runningTime" SET NOT NULL,
ALTER COLUMN "upcBarcode" SET NOT NULL,
ALTER COLUMN "vhsReleaseYear" SET NOT NULL,
ALTER COLUMN "videoStandard" SET NOT NULL,
ALTER COLUMN "languages" SET NOT NULL,
ALTER COLUMN "subtitles" SET NOT NULL; 